### ISSUE TITLE
Using InstallPackage("...git") on a package that was previously install from a tarball gives unhelpful error

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/PackageManager#24]
Example:
```
gap> InstallPackage("automata"); # installs from old location, downloading a tarball
true
gap> InstallPackage("https://github.com/gap-packages/automata.git");
#I  Cloning unsuccessful
false
```

**Comment by mtorpey** [comment]
This is certainly related to Issue #20.  In master, we now capture stdout and stderr, but we don't do anything with them.  I want to make this output accessible, but I don't want to throw too much info at the screen.

I was thinking of resolving this in the following way: log all the output of external commands (`tar`, `git`, `make`) to a file in a temporary directory, and if installing fails, show something like the following:

```
gap> InstallPackage("https://github.com/gap-packages/automata.git");
#I  Cloning unsuccessful
#!  See log file at /tmp/ab322bf/log.txt
false
```
Does this seem reasonable?

**Comment by fingolfin** [comment]
While I think giving the user access to logs for better debugging is helpful, I don't quite see how it applies here: this package does not perform any build steps. The, problem, as far as I can tell, is that `InstallPackageFromGit` runs `git clone  URL`, which tries to create a directory `automata`, but that directory already exists in the example above.

**Comment by fingolfin** [comment]
As such, it is actually related to issue #27

**Comment by mtorpey** [comment]
My point really is responding to the "gives unhelpful error" part of this issue.  If something goes wrong with an external program like git (invalid git link, network interruption, etc.), it should be possible for the user to inspect some log and find out what went wrong.

But I believe you're right, and we should have an actual check before calling `git` to make sure that the directory doesn't already contain something, rather than just calling git and allowing it to fall over.  I'll aim for something like:

```
gap> InstallPackage("https://github.com/gap-packages/automata.git");
#I  Target directory exists and is non-empty:
#I  /home/yourname/.gap/pkg/automata
false
```

**Comment by mtorpey** [comment]
The pre-cloning check is done in 77bb77a.  Other checks to avoid overwriting are Issue #27, and giving useful feedback from failing external programs is Issue #20.  So I'll close this issue!
