### ISSUE TITLE
Difference in behavior between different packages

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/PackageManager#65]
In `CapAndHomalg` I use `GAP.Packages.install(pkg, interactive = false)` to install [this list of GAP package](https://github.com/homalg-project/CapAndHomalg.jl/blob/bfaffb4bf14316a4520897370d47568c27f86f67/deps/homalg-project.jl#L282-L290), which in turn calls `InstallPackage`. I wonder why I get the following different messages for the different packages, although all of them are already installed and loadable?

```
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://homalg-project.github.io/homalg_project/Gauss/PackageInfo.g ...
#I  Downloading archive from URL https://github.com/homalg-project/homalg_project/releases/download/Gauss-2020.10-02/Gauss-2020.10-02.tar.gz ...
#I  Saved archive to /var/folders/z7/br6dwhjj5xn8691ygcnbzxc40000gs/T//tmItoIff/Gauss-2020.10-02.tar.gz
#I  Package already installed at target location
#I  Target directory /Users/xx/.julia/gaproot/v4.11/pkg/Gauss-2020.10-02 exists and is non-empty
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/io/PackageInfo.g ...
#I  The newest version of package "io" is already installed
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/grape/PackageInfo.g ...
#I  The newest version of package "grape" is already installed
#I  Retrieving PackageInfo.g from https://digraphs.github.io/Digraphs/PackageInfo.g ...
#I  Downloading archive from URL https://github.com/digraphs/Digraphs/releases/download/v1.4.0/digraphs-1.4.0.tar.gz ...
#I  Saved archive to /var/folders/z7/br6dwhjj5xn8691ygcnbzxc40000gs/T//tmRMxGiJ/digraphs-1.4.0.tar.gz
#I  Package already installed at target location
#I  Target directory /Users/xx/.julia/gaproot/v4.11/pkg/digraphs-1.4.0 exists and is non-empty
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/ferret/PackageInfo.g ...
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/json/PackageInfo.g ...
#I  The newest version of package "json" is already installed
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/orb/PackageInfo.g ...
#I  The newest version of package "orb" is already installed
```

**Comment by mtorpey** [comment]
Hi Mohamed!

There's a lot going on here, but hopefully I can say a few interesting things about the package manager, and one of them will explain the issue!

The package manager will attempt to install the *latest released version* of any named package.  If it's already installed, then it will skip it, but if there's an *older version* installed, then it will go ahead and install again.  By default, this will be in the `~/.gap/pkg` directory, regardless of where the old version was installed.

The Digraphs package will behave slightly differently from the others here, because your list of packages gives an explicit PackageInfo.g file for it.  So in this case, I believe it doesn't check any version numbers, but just tries to install it.  This might explain some more differences.

Does this help explain things?  If not, maybe you could point to two or three exact lines of output that don't seem right to you.

**Comment by mohamed-barakat** [comment]
I see. This resolves my question. Thank you very much, Michael.
